python: Fix properties test for Python 3.11
This test failed under Python 3.11 due to more detail being
included in tracebacks per PEP 657:

Expected:
    Traceback (most recent call last):
      File "properties.py", line 49, in ?
        x1.value_r = 2
    AttributeError: can't set attribute
Got:
    Traceback (most recent call last):
      File ".../doctest.py", line 1355, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest __main__[16]>", line 1, in <module>
        x1.value_r = 2

The test now uses doctest's IGNORE_EXCEPTION_DETAIL option to
ignore the traceback and only verify that the expected exception
type is raised. This allows the test to work for Python versions
before and after 3.11.

Fixes #3384

(Internal change: 2351567)